services:
  cybertracker_db:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  cybertracker_api:
    user: "0:0"
    environment:
      ENVIRONMENT: dev
      PYTHONPATH: /app
    volumes:
      - ./app:/app/app:rw
      - ./models:/app/models:rw
      - ./alembic:/app/alembic:rw
    command:
      - uvicorn
      - app.main:app
      - --reload
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
